### ISSUE TITLE
Remove user from db in docker services

### ISSUE THREAD

**Issue by klingberg** [Frojd/Frojd-Bedrock#24]
User setting is not working under Linux.

Change:
```
    db:
        image: mysql:5
        ports:
            - "{{cookiecutter.docker_db_port}}:3306"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./db/:/var/lib/mysql"
        env_file: "./docker/config/db.env"
        user: "1000:50"
```
To:
```
    db:
        image: mysql:5
        ports:
            - "{{cookiecutter.docker_db_port}}:3306"
        volumes:
            - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
            - "./db/:/var/lib/mysql"
        env_file: "./docker/config/db.env"
```
